// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvCLtxabMpDj9mxCVUSCFct0ukSD2y_xY',
    appId: '1:470787015862:web:8b9450520262b91ddfd217',
    messagingSenderId: '470787015862',
    projectId: 'sendyakala-e4fe8',
    authDomain: 'sendyakala-e4fe8.firebaseapp.com',
    storageBucket: 'sendyakala-e4fe8.appspot.com',
    measurementId: 'G-NR6K3P90XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYVY3zZhm-ny6QiRnOWD6pS9tgv1neNgk',
    appId: '1:470787015862:android:81d0d134e21bb0fbdfd217',
    messagingSenderId: '470787015862',
    projectId: 'sendyakala-e4fe8',
    storageBucket: 'sendyakala-e4fe8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAorACJv0DkIymPlA6117G6oX4n1reNxY',
    appId: '1:470787015862:ios:bb5c74487e29bbdadfd217',
    messagingSenderId: '470787015862',
    projectId: 'sendyakala-e4fe8',
    storageBucket: 'sendyakala-e4fe8.appspot.com',
    iosBundleId: 'com.example.sendyakala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAorACJv0DkIymPlA6117G6oX4n1reNxY',
    appId: '1:470787015862:ios:bb5c74487e29bbdadfd217',
    messagingSenderId: '470787015862',
    projectId: 'sendyakala-e4fe8',
    storageBucket: 'sendyakala-e4fe8.appspot.com',
    iosBundleId: 'com.example.sendyakala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvCLtxabMpDj9mxCVUSCFct0ukSD2y_xY',
    appId: '1:470787015862:web:29adb9c95399ca40dfd217',
    messagingSenderId: '470787015862',
    projectId: 'sendyakala-e4fe8',
    authDomain: 'sendyakala-e4fe8.firebaseapp.com',
    storageBucket: 'sendyakala-e4fe8.appspot.com',
    measurementId: 'G-FCXFN6SM70',
  );
}
